### ISSUE TITLE
Do we want to move to /pages instead of /docs

### ISSUE THREAD

**Issue by PipeItToDevNull** [r-Techsupport/rTS_Wiki#10]
pages are how Jekyll refers to things, and it may make more sense in the URL

making the move prior to full deployment would be best if we want to do it

**Comment by SealsRock12** [comment]
I would prefer not having a path at all, but still a folder for organization, idk if thet's possible or not

**Comment by PipeItToDevNull** [comment]
I think the method to remove /docs is to put our directories into the root instead of /docs but I think that would be hella messy

**Comment by PipeItToDevNull** [comment]
It was launched, migrating now would cause too many issues IMO
