### ISSUE TITLE
One detail in sub-bullet or in the same question

### ISSUE THREAD

**Issue by SealsRock12** [r-Techsupport/rTS_Wiki#12]
For https://github.com/r-Techsupport/rTS_Wiki/commit/8564b6f4b59cac73b89094a1c5e0c44dd4b90cc4, where there is only one sub-bullet for details, should we have them in the top bullet (older) or as a sub-bullet (newer)?

This is pretty trivial, but I thought I would ask it anyways.

**Comment by PipeItToDevNull** [comment]
It builds on the parent, I think a sub bullet is the only real way to associate that. It used to use commas and be the same bullet but that was a bit long

**Comment by SealsRock12** [comment]
Yeah I intentionally chose the one bullet, I thought it looks better. It would help to get others' opinion on this.

**Comment by SealsRock12** [comment]
https://github.com/r-Techsupport/rTS_Wiki/commit/626f8903a9a9592083712886086a84e1b45a7223

**Comment by SealsRock12** [comment]
On discord, we decided to use the sub-bullet
