### ISSUE TITLE
Update git links to r-techsupport rather than me

### ISSUE THREAD

**Issue by PipeItToDevNull** [r-Techsupport/rTS_Wiki#14]
https://wiki.rtech.support/docs/recommendations/temps-voltages.html

**Comment by SealsRock12** [comment]
This was because the specs factoid pointed to you, I'll change it

**Comment by SealsRock12** [comment]
https://github.com/r-Techsupport/rTS_Wiki/commit/cd6ffcc8824e46bcac99b322a0facd9161439572
https://github.com/r-Techsupport/rTS_Wiki/commit/bbcc3389e30c5c8493d8728890a0116dfd1855a4
