### ISSUE TITLE
Remove LastPass from Password Manager list

### ISSUE THREAD

**Issue by xTobyPlayZ** [r-Techsupport/rTS_Wiki#152]
https://rtech.support/docs/safety-security/pw-managers.html
After the breach it's probably not a good idea to recommend them.

**Comment by PipeItToDevNull** [comment]
If we removed every company who has been breached we will have no companies left. The main mistake they made is not having 2 keys to a vault like Bitwarden does. How many other providers have the same weakness? Its hard to tell and we don't group them by that.

**Comment by WhiteHusky** [comment]
@PipeItToDevNull It's more of a matter of trust being lost and losing trust in your password manager is not exactly a comfortable feeling, especially to continue recommending them after [not being transparent about the situation](https://palant.info/2022/12/26/whats-in-a-pr-statement-lastpass-breach-explained/).

The amount of metering the facet of information is somewhat concerning, along with some questionable items left unencrypted and lacking security practices that the source mentions.
