### ISSUE TITLE
Add RMA and UPS to terms

### ISSUE THREAD

**Issue by PipeItToDevNull** [r-Techsupport/rTS_Wiki#16]
They are used in computing basics and will need to be linked to a definition

**Comment by SealsRock12** [comment]
First we need to figure out how to link to individual terms in the first place

**Comment by PipeItToDevNull** [comment]
Still need to find a way to link specific terms

**Comment by TheKrol** [comment]
Added UPS and RMA to terms, and fix a couple headers in Terms
