### ISSUE TITLE
Password manager article

### ISSUE THREAD

**Issue by PipeItToDevNull** [r-Techsupport/rTS_Wiki#17]
It is mentioned in computing basics and will need to be linked

**Comment by PipeItToDevNull** [comment]
https://github.com/r-Techsupport/rTS_Wiki/commit/443e10b4d4654b3ab0734100d3314f07ad89ad4f

**Comment by SealsRock12** [comment]
https://github.com/r-Techsupport/rTS_Wiki/commit/b6f63ca2d922379a11e5bf65cea0d2ca88c03851

**Comment by PipeItToDevNull** [comment]
https://github.com/r-Techsupport/rTS_Wiki/commit/efa2b879a19bd6885e874b360f9fae82557a80da
