### ISSUE TITLE
Need better picture of 24 pin connector

### ISSUE THREAD

**Issue by Har0ldFinch** [r-Techsupport/rTS_Wiki#179]
https://rtech.support/docs/factoids/hardware-photos.html

The second picture depicting the 24 pin connector is not clear at all and also at a bad angle. I imagine a better approach would be two pictures, one of the connector plugged out from top down and a second one of the connector in the motherboard from a more zoomed out angle.

**Comment by Goldmaster** [comment]
I will have a go at tackling this issue tomorrow.

**Comment by Mr-KayZ** [comment]
Might consider remaking the entire guide if necessary with better pictures
