### ISSUE TITLE
Update icon cache article

### ISSUE THREAD

**Issue by TheKrol** [r-Techsupport/rTS_Wiki#180]
Need to update the icon article to not stop explorer before you use the `win+r` command

**Comment by Har0ldFinch** [comment]
![image](https://user-images.githubusercontent.com/130164717/234132751-54413ae8-8bf2-4557-829b-fca1f68e53d4.png)

You mean move this part to step two after running CMD as admin?

**Comment by TheKrol** [comment]
Yes
