### ISSUE TITLE
Hardware Picture update

### ISSUE THREAD

**Issue by TheKrol** [r-Techsupport/rTS_Wiki#231]
Add a picture of the back of the PC so people know where to plug monitors into the GPU.

**Comment by PipeItToDevNull** [comment]
Numbers are hard

**Comment by Har0ldFinch** [comment]
What article is this for? What about this picture that Krol himself has pinned in the Discord #Hardware channel?

![image](https://github.com/r-Techsupport/rTS_Wiki/assets/130164717/b13a32c1-1356-4a76-97fe-6770aa6169b8)
