### ISSUE TITLE
Diskpart

### ISSUE THREAD

**Issue by TheKrol** [r-Techsupport/rTS_Wiki#236]
Update the diskpart article to more general article with different options like clean and writelock

**Comment by Tomat0r** [comment]
What about merging all the diskpart articles into one thing with proper headers for common things like converting to GPT and cleaning?

**Comment by TheKrol** [comment]
Yeah that is fine, just have a different section for all of them would be nice.

**Comment by PipeItToDevNull** [comment]
This has been made into a factoid in https://github.com/r-Techsupport/rTS_Wiki/pull/267

The GPT and Clean are also factoids, they may be able to be {included} into one article but I think that is a second effort
