### ISSUE TITLE
new memtest section

### ISSUE THREAD

**Issue by PipeItToDevNull** [r-Techsupport/rTS_Wiki#25]
We added [this](https://github.com/stressapptest/stressapptest) to rTS_Debian. 

[ref](https://rog.asus.com/forum/showthread.php?73665-Our-preferred-memory-stress-test)

**Comment by SealsRock12** [comment]
Would it replace the current one, or would we create a memtesting section inside "guides" to have both?

**Comment by PipeItToDevNull** [comment]
def inside for now, it would need more testing to be relied on fully

**Comment by PipeItToDevNull** [comment]
I hid the stressapptest page in dev, but did not remove links to it
