### ISSUE TITLE
Replace warning at top of install 10|11 with callout

### ISSUE THREAD

**Issue by PipeItToDevNull** [r-Techsupport/rTS_Wiki#278]

**Comment by sealsrock12** [comment]
there are info, caution, warning, and danger callouts. I don't think we need a standardized system for then, but perhaps:

Caution - Something that can break a program or cause a minor annoyance.
Warning - Something that can make you lose data or can fry/break a component
Danger - Reserved for something that can cause physical harm to you, for example smashing an open disk

**Comment by PipeItToDevNull** [comment]
> there are info, caution, warning, and danger callouts. I don't think we need a standardized system for then, but perhaps:
> 
> Caution - Something that can break a program or cause a minor annoyance. Warning - Something that can make you lose data or can fry/break a component Danger - Reserved for something that can cause physical harm to you, for example smashing an open disk

@sealsrock12 I don't see these callouts in my testing

**Comment by sealsrock12** [comment]
@PipeItToDevNull 
![image](https://github.com/r-Techsupport/rTS_Wiki/assets/47796480/5c83aac6-a4ba-4772-b14c-f99de01f9bc2)
![image](https://github.com/r-Techsupport/rTS_Wiki/assets/47796480/3107eed0-8e6f-4cae-90a4-cf3b88457c12)

**Comment by sealsrock12** [comment]
and as of https://github.com/r-Techsupport/rTS_Wiki/commit/452e45374919e1f8f5b1e691cf62c215dddd3431:
![image](https://github.com/r-Techsupport/rTS_Wiki/assets/47796480/18101165-a646-4201-8c71-f284cf8762c0)
![image](https://github.com/r-Techsupport/rTS_Wiki/assets/47796480/8245c118-963e-4748-93d5-844d832166a9)
