### ISSUE TITLE
Update Live linux article

### ISSUE THREAD

**Issue by TheKrol** [r-Techsupport/rTS_Wiki#284]
"data retrival"
Need to update the link here to /docs/disks/data-recovery/data-recovery.html

**Comment by PipeItToDevNull** [comment]
I grep'd that and could not find the word

**Comment by TheKrol** [comment]
![image](https://github.com/r-Techsupport/rTS_Wiki/assets/7559922/e891df12-c7c0-4027-971e-dc6d97e740cd)
It would be here

**Comment by Bjoolz** [comment]
Noticed this as well. Direct link: https://rtech.support/docs/disks/data-retrieval.

When opening the page in Github, it just goes to the 404.md.
