### ISSUE TITLE
How to make a share (SMB)

### ISSUE THREAD

**Issue by PipeItToDevNull** [r-Techsupport/rTS_Wiki#32]
An article on how to share a directory on your local network 

Cover:
* Permissions
* Using Microsoft accounts
* The network center is bad, no no use
* how to map via IP to a network drive or just a quick access shortcut

**Comment by T0minat0r** [comment]
[creating-a-smb-share.md](https://github.com/r-Techsupport/rTS_Wiki/files/10577464/creating-a-smb-share.md)
