### ISSUE TITLE
Dislocker

### ISSUE THREAD

**Issue by PipeItToDevNull** [r-Techsupport/rTS_Wiki#34]
Dislocker mounts bitlocker vols in Linux (it is in our ISO)

**Comment by TheKrol** [comment]
Added article for Dislocker mounts

**Comment by PipeItToDevNull** [comment]
https://github.com/r-Techsupport/rTS_Wiki/tree/34-Dislocker

**Comment by PipeItToDevNull** [comment]
Like it, I may redo it with a VM and our ISO

**Comment by TheKrol** [comment]
I added images with our ISO

**Comment by PipeItToDevNull** [comment]
https://github.com/r-Techsupport/rTS_Wiki/pull/96

**Comment by TheKrol** [comment]
@sealsrock12 @PipeItToDevNull are we good here as well?
