### ISSUE TITLE
Password Manager Update doc

### ISSUE THREAD

**Issue by Willzy12h** [r-Techsupport/rTS_Wiki#37]
# Password Managers

Early in 2019, Basecamp and Nest notified that mass break-ins had occurred against their users. It was not because they had a breach; it was not their fault at all. The mass break-ins resulted from a botnet campaign using credentials farmed from other breached companies.

Many people re-use their passwords online, so they can use your ‘leaked’ password on other websites when an account has been breached. Password Breaches are becoming increasingly common and often go unnoticed until they are found on the dark web or have been reported by individuals or organisations “hunting” for vulnerabilities.

---
## Breaches and issues
**haveibeenpwned** is a great site; you can enter your email, and haveibeenpwned will tell you how many breaches it has been exposed to. The site will also tell you what was revealed in that breach, such as **passwords, names, addresses, social security numbers, and other personal information** that you care about. Looking at the front page of haveibeenpwned shows today's magnitude of data breaches. The current count of compromised accounts held by the site is close to 12 billion.

**Collection #1**
In January 2019, an extensive collection of credentials was discovered being distributed on a popular hacking forum. The data contained almost **2.7 billion records, including 773 million unique email addresses alongside passwords** those addresses had been used on other breached services.

**Verifcations.io**
In February 2019, an email validation service called verifications.io suffered a data breach. The breach was due to the data being stored in a database that was left publicly facing without a password, resulting in **763 million unique email addresses being exposed**. Many records within the data also included additional personal attributes such as **names, phone numbers, IP addresses, dates of birth and genders**. No passwords were included in the data. 

---
## What can you do?
**Unique passwords, every site, every time.**

The first step is minimising the impact of an account that has the password stolen, that event is inevitable, and you can do this by ensuring that all sites use unique passwords.

“*But I will never remember that many passwords*" - you don't need to.

I have over 450 sets of credentials and remember 6; the key is writing them down. Yes, writing down passwords is OK*.

There is an asterisk there; of course, it is OK to write down passwords if they are secured. A notebook in a locked cabinet is fine; a sticky note on your monitor is not. We are in the modern age, so we don't use notebooks; we use password managers.

---
## Password Managers

A password manager is a software that holds all your other credentials in a heavily encrypted box. You need to keep track of the **one master password**. The master password should be **extra secure and not guessable** as it unlocks every other password you have saved.

These will all have browser extensions and mobile apps; they auto-fill everything and make life much easier. I never have to remember or type out long passwords.

**Password managers** often generate long, complex passwords that, realistically, will never be guessed or brute forced. When creating a password, or your master password, it is recommended to use a combination of words, special characters and numbers. Below are some examples (**DO NOT USE THE BELOW PASSWORDS**)

    14$Broken$Website$Power$Tree14
    H3cT0rSaid@Story123
    %HotD@ys$Try&StayCool8444

And the next best thing you can do is enable **Multi-Factor Authentication** to your accounts, so if your password is breached, they will still need your phone or another device to access your data.

Check out our article on [MFA](/docs/safety-security/mfa) for the next steps you can take in securing your accounts.

| Product | Online/Offline | |
| --- | --- | --- |
| Bitwarden/Vaultwarden | Online | |
| Lastpass | Online | |
| Myki | Hybrid | |
| Keepass/KeepassXC | Offline | |

**Comment by PipeItToDevNull** [comment]
https://github.com/r-Techsupport/rTS_Wiki/commit/b726cde32eacfad8475cbfea1c3d630f2064e875
