### ISSUE TITLE
Doc for cleaning an old Windows disk (using diskmgmt)

### ISSUE THREAD

**Issue by PipeItToDevNull** [r-Techsupport/rTS_Wiki#41]
It would be under https://rtech.support/docs/disks/disk-management.html most likely

**Comment by Har0ldFinch** [comment]
Do you mean diskpart clean or just show where you can access the disk cleanup option? 

Or something third? I am not quite understanding what you mean.

**Comment by PipeItToDevNull** [comment]
I think this is what I had wanted, I forget lol

https://rtech.support/docs/factoids/diskpart-clean.html
