### ISSUE TITLE
Super basic computing

### ISSUE THREAD

**Issue by PipeItToDevNull** [r-Techsupport/rTS_Wiki#58]
How to install drivers, links to the major manufacturer 

How to install programs (no package managers)

How to uninstall programs cause people be silly 

How to end a process 

Reboot FFS

**Comment by TheKrol** [comment]
Created a branch with the file to look over.

**Comment by PipeItToDevNull** [comment]
How to extract a file

**Comment by TheKrol** [comment]
Added extracting section

**Comment by PipeItToDevNull** [comment]
how to shutdown a computer.....

yes it is needed https://discord.com/channels/749314018837135390/910586244210262017/1020870840235077643

**Comment by sealsrock12** [comment]
Closed in #111
