### ISSUE TITLE
DDU factoid is ddulaptop

### ISSUE THREAD

**Issue by Bjoolz** [r-Techsupport/rTS_Wiki#72]
Add original DDU factoid to article and separate ddulaptop and ddu factoid in the article

**Comment by Daspletosaurid** [comment]
I'm working on writing a new DDU article, I'll have to ask your feedback on how to "compress" it to be more space efficient though

**Comment by Bjoolz** [comment]
Would perhaps consolidate them into one article, but on the steps where laptop and desktop differ, do 

Step X:
    Laptop: <Instructions>  
    Desktop: <Instructions>

**Comment by PipeItToDevNull** [comment]
Should be complete? https://github.com/r-Techsupport/rTS_Wiki/pull/93
