### ISSUE TITLE
BSOD dump instructions

### ISSUE THREAD

**Issue by Bjoolz** [r-Techsupport/rTS_Wiki#88]
https://github.com/r-Techsupport/rTS_Wiki/blob/dev/docs/factoids/bsod.md

Because of OneDrive syncing the desktop on a lot of machines and breaking zipping, I suggest we change "If you have dump files, copy the entire folder (not just the files in the folder) to the desktop. This will require administrator permissions." to "If you have dump files, copy the entire folder (not just the files in the folder) to the Downloads folder. This will require administrator permissions."

**Comment by TheKrol** [comment]
@sealsrock12 You pulled this right?

**Comment by sealsrock12** [comment]
Looks like it
